Add allure reporting and email delivery

diff --git a/.github/workflows/playwrightBasePipeline.yml b/.github/workflows/playwrightBasePipeline.yml
--- a/.github/workflows/playwrightBasePipeline.yml
+++ b/.github/workflows/playwrightBasePipeline.yml
@@ -74,32 +74,28 @@ jobs:
         run: |
           echo "env=${{ inputs.ENV }}" >> ./allure-results/environment.properties
 
+      - name: Generate Allure Report
+        id: allure-report
+        run: |
+          npx allure generate ./allure-results --clean -o allure-report
+
+          REPORT_PATH="${{ inputs.ENV }}/${{ env.FILENAME }}/${{ github.run_number }}"
+
+          echo "REPORT_PATH=$REPORT_PATH" >> $GITHUB_ENV
+
+      - name: Prepare folder structure
+        run: |
+          mkdir -p deploy/${REPORT_PATH}
+          cp -r allure-report/* deploy/${REPORT_PATH}/
+
       - name: Deploy Allure report to GitHub Pages
         uses: peaceiris/actions-gh-pages@v4
         if: always()
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: gh-pages
-          publish_dir: ./allure-report
+          publish_dir: ./deploy
           keep_files: true
-
-      - name: Generate Allure Report
-        id: allure-report
-        run: npx allure generate ./allure-results --clean -o allure-report
-          
-          REPORT_PATH="${{ inputs.ENV }}/${{ env.FILENAME }}/${{ github.run_number }}"
-        
-          echo "reports-site=allure-report" >> $GITHUB_OUTPUT
-          echo "reports-site-path=$REPORT_PATH" >> $GITHUB_OUTPUT
-
-      - name: Deploy Allure report to GitHub Pages
-        uses: peaceiris/actions-gh-pages@v4
-        if: ${{ always() && steps.allure-report.outcome == 'success' }}
-        with:
-          github_token: ${{ secrets.GITHUB_TOKEN }}
-          publish_branch: gh-pages
-          publish_dir: ${{ steps.allure-report.outputs.reports-site }}
-          destination_dir: ${{ steps.allure-report.outputs.reports-site-path }}
 
       - name: Construct Report Path
         id: construct-path
@@ -243,7 +239,7 @@ jobs:
         run: |
           set -e
           
-          SUMMARY=$(jq -e '{total: .statistic.total, passed: .statistic.passed, failed: .statistic.failed, skipped: .statistic.skipped, broken: .statistic.broken, unknown: .statistic.unknown, duration: .time.duration | tostring}' ./downloaded-artifacts/${{ github.run_number }}/widgets/summary.json || echo '{}')
+          SUMMARY=$(jq -e '{total: .statistic.total, passed: .statistic.passed, failed: .statistic.failed, skipped: .statistic.skipped, broken: .statistic.broken, unknown: .statistic.unknown, duration: .time.duration | tostring}' ./downloaded-artifacts/widgets/summary.json || echo '{}')
           
           DURATION_MS=$(echo $SUMMARY | jq -r .duration)
           DURATION=$((DURATION_MS / 1000))
@@ -277,8 +273,8 @@ jobs:
           echo "PASS_RATE=$PASS_RATE" >> $GITHUB_ENV
           
           if [ "$FAILED" -gt 0 ]; then
-            FAILED_TESTS=$(jq -e '[.. | select(.name? | type == "string" and contains(".")) | {test: .name, test_cases: [.children[]? | select(.status == "failed") | .name]}] | map(select(.test_cases | length > 0))' ./downloaded-artifacts/${{ github.run_number }}/data/suites.json || echo '[]')
-            jq -e '[.. | select(.name? | type == "string" and contains(".")) | {error_message: .name, "test_case": ([.children[]?.name])}]' ./downloaded-artifacts/${{ github.run_number }}/data/categories.json > failed_messages.json || echo '[]' > failed_messages.json
+            FAILED_TESTS=$(jq -e '[.. | select(.name? | type == "string" and contains(".")) | {test: .name, test_cases: [.children[]? | select(.status == "failed") | .name]}] | map(select(.test_cases | length > 0))' ./downloaded-artifacts/data/suites.json || echo '[]')
+            jq -e '[.. | select(.name? | type == "string" and contains(".")) | {error_message: .name, "test_case": ([.children[]?.name])}]' ./downloaded-artifacts/data/categories.json > failed_messages.json || echo '[]' > failed_messages.json
             echo "HAS_FAILED_TESTS=true" >> $GITHUB_ENV
             echo "FAILED_TESTS=$(echo "$FAILED_TESTS" | jq -c .)" >> $GITHUB_ENV
           else
